### ISSUE TITLE
Bug - update-via-source instructions buggy

### ISSUE THREAD

**Issue by hildeb** [znuny/manual#1]
### Environment

- OS:           Linux, Ubuntu 18.04 
- Browser:      not applicable
- Znuny version: 6.1.x.

### Expected behaviour

I expect the upgrade instructions to work, in particular this section:

```
# Restore dotfiles from the homedir to the new directory
for f in $(find /opt/otrs -maxdepth 1 -type f -name .\* -not -name \*.dist); do cp -av "$f" /opt/znuny-6.2.1/; done

# Restore modified and custom cron job
for f in $(find /opt/otrs/var/cron -maxdepth 1 -type f -name .\* -not -name \*.dist); do cp -av "$f" /opt/znuny-6.2.1/var/cron/; done

```
These don't do what they're supposed to do IFF /opt/otrs is a symlink -- as the instructions actually recommend a bit later on:

```
# Create a symlink
ln -s /opt/znuny-6.2.1 /opt/otrs

```

### Actual behaviour

The substatement
`find /opt/otrs -maxdepth 1 -type f -name .\* -not -name \*.dist
`
finds nothing, **although** `/opt/otrs/.forward` exists (in my case)

### Additional information

Solution:
Add "-L" option to the find statements:

`-L     Follow symbolic links.
`

**Comment by rkaldung** [comment]
@hildeb Once again, thank you. Fixed with https://github.com/znuny/manual/commit/9482cfc35b1885e60351760dff08d4b76996fb44
