### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by swiftbird07** [znuny/manual#4]
Just a heads-up:
The link given in the installation documentation for Znuny (https://doc.znuny.org/znuny/releases/installupdate/install.html) is outdated:

```
You should be able to access the installer script using:

http://HOSTNAME/otrs/installer.pl

```
but it should be:

`http://HOSTNAME/znuny/installer.pl`

Greetings
Martin

**Comment by rkaldung** [comment]
@maof97 Thank you for reporting. It's fixed with [a8193f4](https://github.com/znuny/manual/commit/a8193f46774e514f011a3529c1b708d3f6e74c6d)
